// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/card/v1/card.proto

package v1

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应消息（统一返回格式）
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码：0-成功，非0-错误
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	Data          *any1.Any              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       // 业务数据（任意类型）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_api_card_v1_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{0}
}

func (x *CommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponse) GetData() *any1.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// 卡片元数据
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags          string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"` // 标签(分号分隔)
	CreateTime    *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	FilePath      string                 `protobuf:"bytes,7,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_api_card_v1_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *Card) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Card) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Card) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Card) GetCreateTime() *timestamp.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Card) GetUpdateTime() *timestamp.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Card) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// 获取单个卡片请求
type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_api_card_v1_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{2}
}

func (x *GetCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

// 获取所有卡片请求
type ListCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsRequest) Reset() {
	*x = ListCardsRequest{}
	mi := &file_api_card_v1_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsRequest) ProtoMessage() {}

func (x *ListCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsRequest.ProtoReflect.Descriptor instead.
func (*ListCardsRequest) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{3}
}

func (x *ListCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCardsRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListCardsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListCardsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// 列表响应数据（用于CommonResponse的data字段）
type ListCardsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Cards         []*Card                `protobuf:"bytes,4,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsData) Reset() {
	*x = ListCardsData{}
	mi := &file_api_card_v1_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsData) ProtoMessage() {}

func (x *ListCardsData) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsData.ProtoReflect.Descriptor instead.
func (*ListCardsData) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{4}
}

func (x *ListCardsData) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCardsData) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListCardsData) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListCardsData) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

// 更新卡片请求
type UpdateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Tags          *string                `protobuf:"bytes,4,opt,name=tags,proto3,oneof" json:"tags,omitempty"`
	FilePath      *string                `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3,oneof" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardRequest) Reset() {
	*x = UpdateCardRequest{}
	mi := &file_api_card_v1_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardRequest) ProtoMessage() {}

func (x *UpdateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UpdateCardRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateCardRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateCardRequest) GetTags() string {
	if x != nil && x.Tags != nil {
		return *x.Tags
	}
	return ""
}

func (x *UpdateCardRequest) GetFilePath() string {
	if x != nil && x.FilePath != nil {
		return *x.FilePath
	}
	return ""
}

// 添加卡片请求
type AddCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags          string                 `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardRequest) Reset() {
	*x = AddCardRequest{}
	mi := &file_api_card_v1_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardRequest) ProtoMessage() {}

func (x *AddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardRequest.ProtoReflect.Descriptor instead.
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{6}
}

func (x *AddCardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddCardRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddCardRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *AddCardRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

// 删除卡片请求
type DeleteCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardRequest) Reset() {
	*x = DeleteCardRequest{}
	mi := &file_api_card_v1_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardRequest) ProtoMessage() {}

func (x *DeleteCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardRequest) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

// 上传文件请求
type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_api_card_v1_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{8}
}

func (x *UploadRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *UploadRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *UploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// 上传文件响应数据（用于CommonResponse的data字段）
type UploadData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"` // 上传后的文件URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadData) Reset() {
	*x = UploadData{}
	mi := &file_api_card_v1_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadData) ProtoMessage() {}

func (x *UploadData) ProtoReflect() protoreflect.Message {
	mi := &file_api_card_v1_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadData.ProtoReflect.Descriptor instead.
func (*UploadData) Descriptor() ([]byte, []int) {
	return file_api_card_v1_card_proto_rawDescGZIP(), []int{9}
}

func (x *UploadData) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

var File_api_card_v1_card_proto protoreflect.FileDescriptor

const file_api_card_v1_card_proto_rawDesc = "" +
	"\n" +
	"\x16api/card/v1/card.proto\x12\acard.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"h\n" +
	"\x0eCommonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"\xfa\x01\n" +
	"\x04Card\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x1b\n" +
	"\tfile_path\x18\a \x01(\tR\bfilePath\")\n" +
	"\x0eGetCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"}\n" +
	"\x10ListCardsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"\x8d\x01\n" +
	"\rListCardsData\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12#\n" +
	"\x05cards\x18\x04 \x03(\v2\r.card.v1.CardR\x05cards\"\xce\x01\n" +
	"\x11UpdateCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x01R\acontent\x88\x01\x01\x12\x17\n" +
	"\x04tags\x18\x04 \x01(\tH\x02R\x04tags\x88\x01\x01\x12 \n" +
	"\tfile_path\x18\x05 \x01(\tH\x03R\bfilePath\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\a\n" +
	"\x05_tagsB\f\n" +
	"\n" +
	"_file_path\"q\n" +
	"\x0eAddCardRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x01(\tR\x04tags\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\",\n" +
	"\x11DeleteCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\"h\n" +
	"\rUploadRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"'\n" +
	"\n" +
	"UploadData\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl2\xe6\x05\n" +
	"\vCardService\x12z\n" +
	"\aGetCard\x12\x17.card.v1.GetCardRequest\x1a\x17.card.v1.CommonResponse\"=\x82\xd3\xe4\x93\x027Z\x1e\x12\x1c/api/card/v1/cards/{card_id}\x12\x15/api/card/v1/get_card\x12v\n" +
	"\tListCards\x12\x19.card.v1.ListCardsRequest\x1a\x17.card.v1.CommonResponse\"5\x82\xd3\xe4\x93\x02/Z\x14\x12\x12/api/card/v1/cards\x12\x17/api/card/v1/list_cards\x12\x89\x01\n" +
	"\n" +
	"UpdateCard\x12\x1a.card.v1.UpdateCardRequest\x1a\x17.card.v1.CommonResponse\"F\x82\xd3\xe4\x93\x02@:\x01*Z!:\x01*\x1a\x1c/api/card/v1/cards/{card_id}\x1a\x18/api/card/v1/update_card\x12v\n" +
	"\aAddCard\x12\x17.card.v1.AddCardRequest\x1a\x17.card.v1.CommonResponse\"9\x82\xd3\xe4\x93\x023:\x01*Z\x17:\x01*\"\x12/api/card/v1/cards\"\x15/api/card/v1/add_card\x12\x83\x01\n" +
	"\n" +
	"DeleteCard\x12\x1a.card.v1.DeleteCardRequest\x1a\x17.card.v1.CommonResponse\"@\x82\xd3\xe4\x93\x02:Z\x1e*\x1c/api/card/v1/cards/{card_id}*\x18/api/card/v1/delete_card\x12Y\n" +
	"\x06Upload\x12\x16.card.v1.UploadRequest\x1a\x17.card.v1.CommonResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/card/v1/uploadB\x19Z\x17my_workflow/api/card/v1b\x06proto3"

var (
	file_api_card_v1_card_proto_rawDescOnce sync.Once
	file_api_card_v1_card_proto_rawDescData []byte
)

func file_api_card_v1_card_proto_rawDescGZIP() []byte {
	file_api_card_v1_card_proto_rawDescOnce.Do(func() {
		file_api_card_v1_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_card_v1_card_proto_rawDesc), len(file_api_card_v1_card_proto_rawDesc)))
	})
	return file_api_card_v1_card_proto_rawDescData
}

var file_api_card_v1_card_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_card_v1_card_proto_goTypes = []any{
	(*CommonResponse)(nil),      // 0: card.v1.CommonResponse
	(*Card)(nil),                // 1: card.v1.Card
	(*GetCardRequest)(nil),      // 2: card.v1.GetCardRequest
	(*ListCardsRequest)(nil),    // 3: card.v1.ListCardsRequest
	(*ListCardsData)(nil),       // 4: card.v1.ListCardsData
	(*UpdateCardRequest)(nil),   // 5: card.v1.UpdateCardRequest
	(*AddCardRequest)(nil),      // 6: card.v1.AddCardRequest
	(*DeleteCardRequest)(nil),   // 7: card.v1.DeleteCardRequest
	(*UploadRequest)(nil),       // 8: card.v1.UploadRequest
	(*UploadData)(nil),          // 9: card.v1.UploadData
	(*any1.Any)(nil),            // 10: google.protobuf.Any
	(*timestamp.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_api_card_v1_card_proto_depIdxs = []int32{
	10, // 0: card.v1.CommonResponse.data:type_name -> google.protobuf.Any
	11, // 1: card.v1.Card.create_time:type_name -> google.protobuf.Timestamp
	11, // 2: card.v1.Card.update_time:type_name -> google.protobuf.Timestamp
	1,  // 3: card.v1.ListCardsData.cards:type_name -> card.v1.Card
	2,  // 4: card.v1.CardService.GetCard:input_type -> card.v1.GetCardRequest
	3,  // 5: card.v1.CardService.ListCards:input_type -> card.v1.ListCardsRequest
	5,  // 6: card.v1.CardService.UpdateCard:input_type -> card.v1.UpdateCardRequest
	6,  // 7: card.v1.CardService.AddCard:input_type -> card.v1.AddCardRequest
	7,  // 8: card.v1.CardService.DeleteCard:input_type -> card.v1.DeleteCardRequest
	8,  // 9: card.v1.CardService.Upload:input_type -> card.v1.UploadRequest
	0,  // 10: card.v1.CardService.GetCard:output_type -> card.v1.CommonResponse
	0,  // 11: card.v1.CardService.ListCards:output_type -> card.v1.CommonResponse
	0,  // 12: card.v1.CardService.UpdateCard:output_type -> card.v1.CommonResponse
	0,  // 13: card.v1.CardService.AddCard:output_type -> card.v1.CommonResponse
	0,  // 14: card.v1.CardService.DeleteCard:output_type -> card.v1.CommonResponse
	0,  // 15: card.v1.CardService.Upload:output_type -> card.v1.CommonResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_card_v1_card_proto_init() }
func file_api_card_v1_card_proto_init() {
	if File_api_card_v1_card_proto != nil {
		return
	}
	file_api_card_v1_card_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_card_v1_card_proto_rawDesc), len(file_api_card_v1_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_card_v1_card_proto_goTypes,
		DependencyIndexes: file_api_card_v1_card_proto_depIdxs,
		MessageInfos:      file_api_card_v1_card_proto_msgTypes,
	}.Build()
	File_api_card_v1_card_proto = out.File
	file_api_card_v1_card_proto_goTypes = nil
	file_api_card_v1_card_proto_depIdxs = nil
}
