app:
  httpPort: 8000
  httpUrl: 127.0.0.1:8000
  rpcPort: 8001
  ai:
  file:
    logPath: storage/logs

# database
mongodb:
  username: xxxxx
  password: xxxxx
  #addr: "mongodb://%s:%s@localhost:27017,localhost:27018,localhost:27019/?replicaSet=rs0&authSource=admin"
  addr: "mongodb://%s:%s@localhost:27017/?authSource=admin&directConnection=true"
  minPoolSize: 10
  maxPoolSize: 100
  maxConnIdleTime: 30
  connectTimeout: 20
  commonDataBase: manage_dev
  cardDataBase: card
